param(
    [Parameter()][String]$CMDCloseXstore,
    [Parameter()][String]$CMDRestartStack,
    [Parameter()][String]$CMDRestartSystem
)

$scriptVer = "v1.4"; #-- Cleanup for GitHub. 
# -- v1.3 Added log below buttons and cleard up code / UI. 
# -- v1.2 Fixed Paramiterisation, as execution was calling UAC. 
# -- v1.1 Paramiterise the program so we can use it in the xenvironment menu.
# -- v1.1 Add option to Restart the Stack within the UI.
# -- v1 - Initial Build.
# ------------------------------------------------------------------------------
# -- This script will gracefully close xstore.
# -- Scott Powdrill 2023.

#Logging path
$loggingpath = '\\dhl-fs01\XStoreTillBackups\Close-Xstore-Xenviron-log.txt';

Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName PresentationCore
Add-Type -AssemblyName WindowsBase
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

# Main Form 
$form = New-Object System.Windows.Forms.Form
$form.Font = New-Object System.Drawing.Font("Century Gothic",10,[System.Drawing.FontStyle]::Regular)
$form.Text = 'xStore Controller'
$form.Size = New-Object System.Drawing.Size(475,355)
$form.StartPosition = 'CenterScreen'
$Form.FormBorderStyle = 'Fixed3D'
$Form.MaximizeBox = $false

# Log Window
$Listview = New-Object System.Windows.Forms.ListView 
$Listview.Location = New-Object System.Drawing.Size(10,170)
$Listview.Size = New-Object System.Drawing.Size(440,120)
$listView.Columns.Add("Events")
$Listview.AutoArrange=$true
$Listview.GridLines=$true
$Listview.MultiSelect=$false
$listView.View = "Details"
$listView.FullRowSelect =$true
$listView.Columns[0].Width = 415

# Titlebar Icon
$iconBase64      = 'AAABAAEAYGAAAAEAIAColAAAFgAAACgAAABgAAAAwAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD007R1AMeuqPzHq8UAy6/9AMuv/QDLq/0Ax6v8/Mer/PzHq/z8x6v8/MOr/PzDq/z4w6v8+MOr/PjDq/z4v6v8+L+r/PS/q/z0v6v89Lun/PS7p/z0u6f88Lun/PC7p/zwt6f88Len/PC3p/zst6f87LOn/Oyzp/zss6f87LOn/Oizp/zor6f86K+j/Oivo/zor6P85K+j/OSro/zkq6P85Kuj/OSro/zgp6P84Kej/OCno/zgp6P84Kej/Nyjo/zco6P83KOf/Nyjn/zcn5/82J+f/Nifn/zYn5/82J+f/Nibn/zUm5/81Juf/NSbn/zUl5/81Jef/NCXn/zQl5v80Jeb/NCTm/zQk5v8zJOb/MyTm/zMj5v8zI+b/MyPm/zMj5v8yI+b/MiLm/zIi5v8yIub/MiLm/zEh5f8xIeX/MSHl/zEh5f8xIeX/Lx/k8TAf5aktJOMcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQTTrJ0Ez6u5BM+v/QTPr/0Ez6/9BMuv/QDLr/0Ay6/9AMuv/QDLq/0Ax6v8/Mer/PzHq/z8x6v8/MOr/PzDq/z4w6v8+MOr/PjDq/z4v6v8+L+r/PS/q/z0v6v89L+r/PS7p/z0u6f88Lun/PC7p/zwt6f88Len/PC3p/zst6f87Len/Oyzp/zss6f87LOn/Oizp/zor6f86K+j/Oivo/zor6P85K+j/OSro/zkq6P85Kuj/OSro/zgp6P84Kej/OCno/zgp6P84Kej/Nyjo/zco6P83KOf/Nyjn/zcn5/82J+f/Nifn/zYn5/82J+f/Nibn/zUm5/81Juf/NSbn/zUl5/81Jef/NSXn/zQl5v80Jeb/NCTm/zQk5v80JOb/MyTm/zMj5v8zI+b/MyPm/zMj5v8yI+b/MiLm/zIi5v8yIub/MiLm/zEh5f8xIeX/MSHl/zEh5f8wIeXsLSTjHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQTTqr0I06/9CNOv/QjTr/0Ez6/9BM+v/QTPr/0Ez6/9BMuv/QDLr/0Ay6/9AMuv/QDLq/0Ax6v8/Mer/PzHq/z8x6v8/Mer/PzDq/z4w6v8+MOr/PjDq/z4v6v8+L+r/PS/q/z0v6v89L+r/PS7p/z0u6f88Lun/PC7p/zwt6f88Len/PC3p/zst6f87Len/Oyzp/zss6f87LOn/Oizp/zor6f86K+j/Oivo/zor6P85K+j/OSro/zkq6P85Kuj/OSro/zgp6P84Kej/OCno/zgp6P84Kej/Nyjo/zco6P83KOf/Nyjn/zcn5/83J+f/Nifn/zYn5/82J+f/Nibn/zYm5/81Juf/NSbn/zUl5/81Jef/NSXn/zQl5v80Jeb/NCTm/zQk5v80JOb/MyTm/zMk5v8zI+b/MyPm/zMj5v8yI+b/MiLm/zIi5v8yIub/MiLm/zEi5f8xIeX/MCHlqQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQzTq8kM16/9CNev/QjTr/0I06/9CNOv/QjTr/0Ez6/9BM+v/QTPr/0Ez6/9BM+v/QDLr/0Ay6/9AMuv/QDLq/0Ax6v8/Mer/PzHq/z8x6v8/Mer/PzDq/z4w6v8+MOr/PjDq/z4v6v8+L+r/PS/q/z0v6v89L+r/PS7p/z0u6f88Lun/PC7p/zwt6f88Len/PC3p/zst6f87Len/Oyzp/zss6f87LOn/Oizp/zor6f86K+j/Oivo/zor6P85K+j/OSro/zkq6P85Kuj/OSro/zgp6P84Kej/OCno/zgp6P84Kej/OCjo/zco6P83KOf/Nyjn/zcn5/83J+f/Nifn/zYn5/82J+f/Nibn/zYm5/81Juf/NSbn/zUm5/81Jef/NSXn/zQl5/80Jeb/NCTm/zQk5v80JOb/MyTm/zMk5v8zI+b/MyPm/zMj5v8yI+b/MiLm/zIi5v8yIub/MSLl8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQzbs/0M17P9DNez/QzXs/0M16/9CNev/QjTr/0I06/9CNOv/QjTr/0Ez6/9BM+v/QTPr/0Ez6/9BM+v/QDLr/0Ay6/9AMuv/QDLq/0Ax6v8/Mer/PzHq/z8x6v8/Mer/PzDq/z4w6v8+MOr/PjDq/z4v6v8+L+r/PS/q/z0v6v89L+r/PS7p/z0u6f88Lun/PC7p/zwt6f88Len/PC3p/zst6f87Len/Oyzp/zss6f87LOn/Oizp/zor6f86K+j/Oivo/zor6P86K+j/OSro/zkq6P85Kuj/OSro/zkp6P84Kej/OCno/zgp6P84Kej/OCjo/zco6P83KOf/Nyjn/zco5/83J+f/Nifn/zYn5/82J+f/Nibn/zYm5/81Juf/NSbn/zUm5/81Jef/NSXn/zQl5/80Jeb/NCTm/zQk5v80JOb/MyTm/zMk5v8zI+b/MyPm/zMj5v8yI+b/MiLm/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARDbs/0Q27P9ENuz/Qzbs/0M17P9DNez/QzXs/0M16/9CNev/QjTr/0I06/9CNOv/QjTr/0Ez6/9BM+v/QTPr/0Ez6/9BM+v/QDLr/0Ay6/9AMuv/QDLq/0Ax6v8/Mer/PzHq/z8x6v8/Mer/PzDq/z4w6v8+MOr/PjDq/z4v6v8+L+r/PS/q/z0v6v89L+r/PS7p/z0u6f88Lun/PC7p/zwt6f88Len/PC3p/zwt6f87Len/Oyzp/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSro/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCjo/zco6P83KOf/Nyjn/zco5/83J+f/Nifn/zYn5/82J+f/Nibn/zYm5/81Juf/NSbn/zUm5/81Jef/NSXn/zQl5/80Jeb/NCTm/zQk5v80JOb/MyTm/zMk5v8zI+b/MyPm/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARTfs/0Q37P9EN+z/RDbs/0Q27P9ENuz/Qzbs/0M17P9DNez/QzXs/0M16/9CNev/QjTr/0I06/9CNOv/QjTr/0Ez6/9BM+v/QTPr/0Ez6/9BM+v/QDLr/0Ay6/9AMuv/QDLq/0Ax6v8/Mer/PzHq/z8x6v8/Mer/PzDq/z4w6v8+MOr/PjDq/z4v6v8+L+r/PS/q/z0v6v89L+r/PS7p/z0u6f89Lun/PC7p/zwu6f88Len/PC3p/zwt6f87Len/Oyzp/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSro/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCjo/zco6P83KOf/Nyjn/zco5/83J+f/Nifn/zYn5/82J+f/Nibn/zYm5/81Juf/NSbn/zUm5/81Jef/NSXn/zQl5/80Jeb/NCTm/zQk5v80JOb/MyTm/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARTjs/0U37P9FN+z/RTfs/0Q37P9EN+z/RDbs/0Q27P9ENuz/Qzbs/0M17P9DNez/QzXs/0M16/9CNev/QjTr/0I06/9CNOv/QjTr/0Ez6/9BM+v/QTPr/0Ez6/9BM+v/QDLr/0Ay6/9AMuv/QDLq/0Ay6v8/Mer/PzHq/z8x6v8/Mer/PzDq/z8w6v8+MOr/PjDq/z4w6v8+L+r/Pi/q/z0v6v89L+r/PS7p/z0u6f89Lun/PC7p/zwu6f88Len/PC3p/zwt6f87Len/Oyzp/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSro/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCjo/zco6P83KOf/Nyjn/zco5/83J+f/Nifn/zYn5/82J+f/Nibn/zYm5/81Juf/NSbn/zUm5/81Jef/NSXn/zQl5/80Jeb/NCTm/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARjjt/0Y47P9FOOz/RTjs/0U37P9FN+z/RTfs/0Q37P9EN+z/RDbs/0Q27P9ENuz/Qzbs/0M17P9DNez/QzXs/0M16/9CNev/QjTr/0I06/9CNOv/QjTr/0E06/9BM+v/QTPr/0Ez6/9BM+v/QTLr/0Ay6/9AMuv/QDLr/0Ay6v9AMer/PzHq/z8x6v8/Mer/PzDq/z8w6v8+MOr/PjDq/z4w6v8+L+r/Pi/q/z0v6v89L+r/PS7p/z0u6f89Lun/PC7p/zwu6f88Len/PC3p/zwt6f87Len/Oyzp/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSro/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCjo/zco6P83KOf/Nyjn/zco5/83J+f/Nifn/zYn5/82J+f/Nibn/zYm5/81Juf/NSbn/zUm5/81Jef/NSXn/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARjnt/0Y57f9GOe3/Rjjt/0Y47P9FOOz/RTjs/0U37P9FN+z/RTfs/0Q37P9EN+z/RDbs/0Q27P9ENuz/Qzbs/0M27P9DNez/QzXs/0M16/9CNev/QjTr/0I06/9CNOv/QjTr/0I06/9BM+v/QTPr/0Ez6/9BM+v/QTLr/0Ay6/9AMuv/QDLr/0Ay6v9AMer/PzHq/z8x6v8/Mer/PzDq/z8w6v8+MOr/PjDq/z4w6v8+L+r/Pi/q/z0v6v89L+r/PS7p/z0u6f89Lun/PC7p/zwu6f88Len/PC3p/zwt6f87Len/Oyzp/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSro/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCno/zco6P83KOj/Nyjn/zco5/83J+f/Nifn/zYn5/82J+f/Nifn/zYm5/81Juf/NSbn/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARzrt/0c67f9HOe3/Rjnt/0Y57f9GOe3/Rjjt/0Y47f9FOOz/RTjs/0U47P9FN+z/RTfs/0Q37P9EN+z/RDbs/0Q27P9ENuz/RDbs/0M27P9DNez/QzXs/0M16/9DNev/QjTr/0I06/9CNOv/QjTr/0I06/9BM+v/QTPr/0Ez6/9BM+v/QTLr/0Ay6/9AMuv/QDLr/0Ay6v9AMer/PzHq/z8x6v8/Mer/PzDq/z8w6v8+MOr/PjDq/z4w6v8+L+r/Pi/q/z0v6v89L+r/PS7p/z0u6f89Lun/PC7p/zwu6f88Len/PC3p/zwt6f87Len/Oyzp/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSvo/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCno/zco6P83KOj/Nyjn/zco5/83J+f/Nifn/zYn5/82J+f/Nifn/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASDrt/0c67f9HOu3/Rzrt/0c67f9HOe3/Rjnt/0Y57f9GOe3/Rjjt/0Y47f9GOOz/RTjs/0U47P9FN+z/RTfs/0U37P9EN+z/RDbs/0Q27P9ENuz/RDbs/0M27P9DNez/QzXs/0M16/9DNev/QjTr/0I06/9CNOv/QjTr/0I06/9BM+v/QTPr/0Ez6/9BM+v/QTLr/0Ay6/9AMuv/QDLr/0Ay6v9AMer/PzHq/z8x6v8/Mer/PzDq/z8w6v8+MOr/PjDq/z4w6v8+L+r/Pi/q/z0v6v89L+r/PS7p/z0u6f89Lun/PC7p/zwu6f88Len/PC3p/zwt6f87Len/Oy3p/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSvo/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCno/zco6P83KOj/Nyjn/zco5/83J+f/Nifn/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASDvt/0g77f9IO+3/SDrt/0c67f9HOu3/Rzrt/0c67f9HOe3/Rznt/0Y57f9GOe3/Rjjt/0Y47f9GOOz/RTjs/0U47P9FN+z/RTfs/0U37P9EN+z/RDbs/0Q27P9ENuz/RDbs/0M27P9DNez/QzXs/0M16/9DNev/QjTr/0I06/9CNOv/QjTr/0I06/9BM+v/QTPr/0Ez6/9BM+v/QTLr/0Ay6/9AMuv/QDLr/0Ay6v9AMer/PzHq/z8x6v8/Mer/PzHq/z8w6v8+MOr/PjDq/z4w6v8+L+r/Pi/q/z0v6v89L+r/PS/q/z0u6f89Lun/PC7p/zwu6f88Len/PC3p/zwt6f87Len/Oy3p/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSvo/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCno/zco6P83KOj/Nyjn/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASTzu/0k87v9JO+3/SDvt/0g77f9IO+3/SDrt/0g67f9HOu3/Rzrt/0c67f9HOe3/Rznt/0Y57P9FOev/RTfq/0U46/9GOOv/RTjs/0U47P9FN+z/RTfs/0U37P9EN+z/RDbs/0Q27P9ENuz/RDbs/0M27P9DNez/QzXs/0M16/9DNev/QjTr/0I06/9CNOv/QjTr/0I06/9BM+v/QTPr/0Ez6/9BM+r/QDPp/z8x6P8/Mun/QDLq/0Ay6v9AMer/PzHq/z8x6v8/Mer/PzHq/z8w6v8+MOr/PjDq/z4w6v8+L+r/Pi/p/z0v6P88Luf/PS/o/z0u5/89Lun/PC7p/zwu6f88Len/PC3p/zwt6f87Len/Oy3p/zss6f87LOn/Oyzp/zos6f86K+n/Oivo/zor6P86K+j/OSvo/zkq6P85Kuj/OSro/zkq6P84Kej/OCno/zgp6P84Kej/OCno/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASjzu/0k87v9JPO7/STzu/0k87v9JO+3/SDvt/0g77f9IO+3/SDrt/0c56v9FOOb/RDfj/0Q34f9DNuD/QzXf/0I24P9DNuH/QzXi/0Q25f9FN+f/RTjr/0M25v9CNOH/QjTh/0I04f9BNOH/QTTh/0Ez4f9BM+H/QTPh/0Az4f9AM+H/QDPh/0Az4v9BNOX/QjXr/0I06/9CNOr/QDPl/z8y4v8+Md//PjHe/z0w3f8+Md7/PjHf/z0w4v8+MeX/PzLp/0Ay6v9AMer/PzHq/z8x6v8/Mer/PjDl/z0u4/87LuD/Oy7e/zsu3f86LNz/Oy3d/zot3v86Ld//Oy3i/zwt5P89Lun/PC7p/zwu6f87LOT/OSvf/zkr3v84K97/OCve/zgq3v84Kt7/OCre/zcq3v83Kd7/Nynd/zcp3f83Kd3/Nyrh/zkq6P85Kuj/OSro/zkq6P85Kej/OCno/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASj3u/0o97v9KPe7/Sjzu/0k87v9JPO7/STzu/0k87v9IO+v/RTnl/0Q44P9DNtz/QjXY/1NG2/9jWd7/bGLg/19U3f9OQdr/QTTY/0E02v9CNd7/Qzbi/0I14P9AM9f/PzPW/z8z1v8/Mtb/PzLW/z8y1v8+Mtb/PjLW/z4x1v8+Mdb/PjHW/z0x1/9AM+D/QjXq/0I05/9AM+H/PjLc/z0w2P9EONf/W1Dc/2hf3/9cUtz/RzzY/zwv1/89MNv/PjHf/z4x5f9AMur/QDLr/0Ay6f89L+H/Oy7c/zou2P85LdX/RDnX/1dM2/9lXN//WlDc/0c82P84K9X/OSzY/zks3P87LeH/PS/o/z0u5/86LN3/NyrU/zYq1P82KdT/NinU/zYp1P81KdT/NSnU/zUo1P81KNT/NSjU/zUo1P80J9T/Nina/zkq5P86K+j/Oivo/zkq6P85Kuj/OSro/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASz7u/0o97v9KPe7/Sj3u/0o97v9KPe7/Sjzu/0g76/9GOeT/RDfd/1NH2/+noe3/5OL5////////////////////////////8vH8/8C88v9mWt//QzXe/0I13v+Lg+f//////////////////////////////////////////////////////3Fn4f9AMt7/QTTj/z8y3v89Mdj/d27i/8vI9P/6+f7//////////////////f3//9bU9v+Mheb/PzPX/z0w3P8+MeL/QTPq/z8x5/88L9z/Vkzb/7Sv7//s6/v////////////////////////////y8fz/trLw/1pQ3P85LNj/Oy3g/zwu5P85LNz/bmXh//////////////////////////////////////////////////////+Si+j/NynZ/zor5P86LOn/Oivp/zor6P86K+j/Oivo/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASz7u/0s+7v9LPu7/Sz7u/0o97v9KPe7/ST3s/0c65P9EONv/gXjl//X1/f////////////////////////////////////////////////+emOv/Qjbd/0M23v+Mg+f//////////////////////////////////////////////////////3Fo4f9AM97/QDPd/0k82P/GwvP/////////////////////////////////////////////////4N/4/1lP2/89MNv/PjHi/z8y5f89MNz/jIXm//////////////////////////////////////////////////r6/v9+duT/OS3Y/zsu3/86Ldz/b2Xh//////////////////////////////////////////////////////+Si+j/NyrZ/zor5P87LOn/Oyzp/zss6f86LOn/Oivp/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATD/v/0s/7/9LPu7/Sz7u/0s+7v9LPu7/SDzl/0U53P+Hfub//v7///////////////////////////////////////////////////////+fmOv/Qzfd/0Q23v+MhOf//////////////////////////////////////////////////////3Fp4f9BM93/RzrY/9nX9/////////////////////////////////////////////////////////////Hw/P9bUdz/PjHc/z8y4f89MNz/jIXm///////////////////////y8fz////////////////////////////6+f7/WE7c/zst3P87Ldz/b2bh//////////////////////////////////////////////////////+SjOj/OCrZ/zss5P88Len/Oy3p/zss6f87LOn/Oyzp/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATD/v/0w/7/9MP+//TD/v/0s/7/9KPer/Rjrg/19V3v/49/3//////////////////////+Hf+f+blOr/enHj/3dt4/+Nhuf/rKbu/+ro+/+fmOv/Qzfd/0Q33v+MhOf/////////////////zcr0/3Rq4v90aeL/dGni/3Np4v9zaeL/c2ni/01B2v9AM9f/t7Pw///////////////////////c2vj/jYbn/3Fn4f99dOP/uLPw//39///////////////////f3fj/QzjX/z8y3/8+Mdz/jYbm//j4/v+tqO3/aF7f/z4y1v87L9X/QDXW/3104//z8/3/////////////////pZ/s/zou2f87Ltz/b2fh/////////////////9za+P9tZOD/bWTg/21k4P9sZOD/bGTg/2xj3/9PRNn/OSva/zst5P88Lun/PC3p/zwt6f88Len/Oy3p/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATEDv/0xA7/9MP+//TD/v/0w/7/9JPef/RTrc/7q28f//////////////////////rqju/0Y62f9FOd7/Rjng/0Y54P9GOd//RTjc/0c62f9bT93/RTjf/0U43/+NhOf/////////////////u7bx/0M12v9DNt//Qzbf/0M23/9DNd//QzXf/0I13v9iWN7//v7//////////////////8C88f9CNtj/QTPd/0Ez3v9AM93/PzLZ/3hu4v/8/P7/////////////////kIno/z4y3P8/Mtz/bWTf/1hN2/89MNn/PjHd/z8y3/8/MuD/PjHg/zwv2f+knuv/////////////////x8Tz/zsu2P88L9z/cGfh/////////////////8/M9f86LNb/Oi3c/zot3P86Ldz/Oizc/zos3P85LNz/Oi3g/z0u6P89Lun/PS7p/zwu6f88Lun/PC3p/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATUDv/01A7/9NQO//TEDv/0xA7v9IPOP/Sz/a//n5/v/////////////////IxPT/RTra/0c74v9HO+P/Rzvj/0c74/9HOuP/Rzrj/0c64v9GOd//Rzrj/0U43/+Nhef/////////////////u7bx/0M22/9FOeX/Rzrq/0c56v9GOer/RDjl/0I13P+wq+7/////////////////7Or7/0o92f9CNeD/QjXh/0I14f9CNeH/QjTh/0Ay2f+rpe3/////////////////4+H5/z4x1/9AM+D/PjHa/z8y3f9AM+D/QDPg/z8y4P8/MuD/PjHd/z4y1v/HxPP/////////////////zsv0/zwu2P88L93/cGfh/////////////////8/M9f86Ldf/PC/f/zwu3/88Lt//Oy7f/zsu4P88L+T/Pi/p/z4v6v89L+r/PS/q/z0u6f89Lun/PS7p/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATUHv/01B7/9NQO//TUDv/0w/7P9IPOH/dGvj//////////////////////9rYeH/Rzvh/0c85P9HO+P/Rzvj/0c74/9HO+P/Rzvj/0c74/9HOuP/Rzrj/0Y53/+Nhef/////////////////u7bx/0Q33P9HOuf/SDvt/0g77f9IO+3/RTnk/0I12f/i4Pn/////////////////o53s/0I13P9DNuL/Qzbi/0M14v9DNeL/QzXh/0E13/9bUdz//////////////////////1VK2/9AM9//QTPh/0Ez4f9AM+H/QDPh/z8y3v8+Mdn/UkfZ/8C88f//////////////////////r6ru/zww2v89MN3/cWjh/////////////////8/M9f86LtX/Oy7Z/zou2f86Ltn/Oi7Z/zot2f88Lt3/PS/m/z4w6v8+MOr/Pi/q/z4v6v89L+r/PS/q/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATkHv/05B7/9OQe//TUHv/0xA6/9IPeD/i4Pn//////////////////Dw/P9GOtr/SDzk/0g85P9IPOT/SDzk/0c85P9HO+P/Rzvj/0c74/9HO+P/Rzvj/0Y63/+Nhef/////////////////vLfx/0Q33P9HOuf/STzu/0k87v9JPO7/RTji/0M42P/9/f//////////////////dm3i/0M23v9EN+L/RDbi/0Q24v9DNuL/Qzbi/0M14v9AM9f/8O/8/////////////////3py4/9BM93/QTTh/0Ez4f9AMt7/PzHZ/11S3f+yre//+Pj+///////////////////////9/f//Ylnd/z4x3P8+Md3/cWjh/////////////////+zr+/+wq+7/sKvu/7Cr7v+wq+7/sKvu/4F65P86Ltn/PTDk/z8x6v8/MOr/PjDq/z4w6v8+MOr/Pi/q/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATkLw/05C8P9OQvD/TkHv/0xA6v9JPeD/l5Dq/////////////////93b+P9GO9v/ST3k/0g95P9IPOT/SDzk/0g85P9IPOT/SDzk/0c85P9HO+P/Rzvj/0Y63/+Nhuf/////////////////vLfx/0U43P9IO+f/Sj3u/0o87v9JPO3/Rjni/1BD2///////////////////////ZFne/0Q23/9FN+L/RDfi/0Q34v9EN+L/RDbi/0Q24v9ANNn/3934/////////////////4qD5v9BNN3/QjTh/0Ez3f9RRdr/t7Pw//39//////////////////////////////z8/v+Oh+f/PjHY/z8z4P8+Md3/cmnh/////////////////////////////////////////////////7Kt7/87L9n/PjDk/z8x6v8/Mer/PzHq/z8x6v8/MOr/PjDq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT0Lw/09C8P9PQvD/TkLw/0xB6/9JPuH/jobo/////////////////9/d+P9GPNv/ST3k/0k95P9JPeT/ST3k/0g95P9IPeT/SDzk/0g85P9IPOT/SDzk/0Y74P+Nhuf/////////////////vLfx/0U53P9IO+f/Sj3u/0o97v9KPe7/Rzrj/0s92f//////////////////////Zlre/0Q33/9FOOL/RTji/0U34v9FN+L/RDfi/0Q34v9BNdn/4N75/////////////////4+H5/9CNN7/QjTd/1xS3P/n5fr/////////////////////////////////4d/5/29m4P8+Mdn/QDPg/0Az4f8/Mt7/cmrh/////////////////////////////////////////////////7Kt7/87L9r/PjHl/0Ay6/9AMur/QDHq/z8x6v8/Mer/PzHq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT0Pw/09D8P9PQ/D/T0Lw/05B7P9KPuH/fXXl//////////////////b1/f9KPtv/ST7k/0k+5P9JPuT/ST3k/0k95P9JPeT/ST3k/0g95P9IPeT/SDzk/0c74P+Oh+j/////////////////vLfx/0U53P9JPOf/Sz7u/0s+7v9KPe7/Rzrk/0Q32f/39v3/////////////////eXDj/0U43/9GOeP/Rjji/0U44v9FOOL/RTji/0U44v9DNdf/8/L8/////////////////4B35P9CNd7/QTXY/9jV9////////////////////////////9za+P+Ee+X/QDTX/0Az3f9BM+H/QTPh/0Ez4f8/Mt7/cmrh/////////////////+/u/P++uvH/vrrx/7668f++uvH/vrrx/4uE5v88MNr/PzLl/0Ez6/9AMuv/QDLr/0Ay6/9AMur/QDHq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUETw/1BD8P9PQ/D/T0Pw/05C7v9LQOT/VUvd//79//////////////////93b+T/ST3g/0o+5P9KPuT/ST7k/0k+5P9JPuT/ST3k/0k95P9JPeT/ST3k/0c84P+Oh+j/////////////////vLjx/0U63f9JPej/Sz7u/0s+7v9LPu7/SDzl/0Q52//Szvb/////////////////qKLt/0U43f9GOeP/Rjnj/0Y54/9GOeP/Rjjj/0Q33/9gVd3//////////////////////2RZ3v9CNt3/cWfh///////////////////////n5fr/enHi/z8z1/9ANNz/QjTg/0I04f9CNOH/QTTh/0E04f9AMt7/c2rh/////////////////9DN9f89Mdf/PjHZ/z0x2f89MNn/PTDZ/z0w2f8+Md3/QDLm/0Ez6/9BM+v/QTPr/0Ez6/9AMuv/QDLr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUETw/1BE8P9QRPD/UETw/1BD8P9MQOf/SD3c/9TS9v/////////////////X1Pf/S0Dc/0k/4/9KP+X/Sj7k/0o+5P9KPuT/Sj7k/0k+5P9IPeH/ST3k/0g84P+Ph+j/////////////////vLjx/0Y63f9KPej/TD/v/0w/7/9LP+//STzn/0U63v+fmev/////////////////7u37/09D2v9GOuH/Rzrj/0c64/9GOeP/Rjnj/0Q32/+sp+7/////////////////8O/8/0M42P9DNt3/kYro//////////////////X1/f9TSNv/QTXd/0M24v9DNeL/QzXh/0I14f9CNeD/QjTg/0I04f9BM97/c2rh/////////////////9DN9f8+Mdn/QDPh/0Az4f9AM+H/QDPg/z8z4P9AM+X/QjTr/0I06/9CNOv/QTPr/0Ez6/9BM+v/QTPr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUUXx/1FE8P9QRPD/UETw/1BE8P9OQur/S0Dh/3525f//////////////////////wr7z/09E3P9JPd//ST7h/0k+4v9JPuH/SD3f/0g92v9YTd3/ST3g/0g94P+PiOj/////////////////vLjx/0Y73f9KPuj/TD/v/0w/7/9MP+//Sz7s/0c84v9VS9z/+Pj+/////////////////8TB8/9IPNr/RTne/0Y54P9GOd//RDjb/3dt4//7+/7/////////////////p6Dt/0M22/9EN97/lIzo/////////////////9/d+P9BNdj/RDbh/0Q24v9DNuL/Qjbg/0E13f9EONn/QDPY/0I14f9BNN7/dGrh/////////////////9DN9f8+Mdj/QDLd/0Ay3f8/Mt3/PzLd/z8y3f8/M9//QTTl/0I16/9CNOv/QjTr/0I06/9CNOv/QTTr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUUXx/1FF8f9RRfH/UUXx/1FE8P9QRO//TUHm/0k+3P/EwfP//////////////////////+zq+/+kn+3/fHXl/3Rs4/+Jguf/pJ/t/+bl+v+hnOz/SD3f/0k94P+PiOj/////////////////vLjx/0c73f9LPuj/TUDv/0xA7/9MQO//TD/v/0k95/9GOt3/oJrs///////////////////////f3fj/kIno/3Jp4v98c+T/sq3v//z8/v/////////////////w7vz/U0fb/0U54f9FOOD/cWfi//////////////////////+mn+z/UUba/0E12P9BNNf/XFDd/5OL6P/j4fn/QDPX/0M24v9CNN//dGvh/////////////////+De+P9/duT/fnbk/3525P9+duT/fnbk/3525P9ANNj/QDPh/0M17P9DNez/QzXr/0M16/9CNOv/QjTr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUkbx/1JF8f9RRfH/UUXx/1FF8f9RRfH/T0Ts/0xA4/9RR9z/2Nb3//////////////////////////////////////////////////////+hnOz/SD7g/0k+4f+PiOn/////////////////vbjx/0c83f9LP+j/TUDv/01A7/9NQO//TUDv/0s/7P9IPeP/Rjva/8bC8/////////////////////////////////////////////////////////////v7/v93beP/RTne/0c75v9GOeP/RDjZ/9jV9/////////////////////////////b1/f/6+f7////////////+/f//QTTX/0Q24v9CNd//dGvi//////////////////////////////////////////////////////9GOtj/QTPg/0Q26/9ENuz/Qzbs/0M17P9DNez/QzXr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUkbx/1JG8f9SRvH/Ukbx/1JF8f9RRfH/UUXx/09D6v9MQeP/UEbd/7y48f/+/v////////////////////////////////////////////+hnOz/ST7g/0o+4f+PiOn/////////////////vbny/0g83f9MP+j/TkHv/01B7/9NQe//TUDv/01A7/9LPun/SD3i/0k+2/+0r/D//v7/////////////////////////////////////////////8vH8/3Vs4v9FOdz/Rzrk/0o97f9IPOj/Rjnf/1tQ3f/i3/n////////////////////////////////////////////+/f//QTTX/0Q34v9DNt//dWzi//////////////////////////////////////////////////////9HO9j/QjTg/0Q36/9ENuz/RDbs/0Q27P9ENuz/Qzbs/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU0fx/1JH8f9SRvH/Ukbx/1JG8f9SRvH/Ukbx/1JF8f9PQ+r/TEHk/0o/3f9vZ+L/v7zy//Hw/P///////////////////////v7//+Hf+f+Ce+b/ST7g/0o/4f+Pien/////////////////vbny/0g93v9MQOj/TkLw/05B7/9OQe//TkHv/01B7/9NQe//Sz/p/0g94v9GO9v/bmTh/8O/8//19P3//////////////////////+fl+v+nou3/UUbb/0U63v9IO+T/Sj7s/0s+7v9LPu7/Rzvm/0Y53/9LP9r/m5Tq/+De+f////////////////////////////Tz/f/EwPL/QjXX/0U44v9ENt//dmzi//////////////////////////////////////////////////////9HPNj/QjXg/0U36/9FN+z/RTfs/0Q37P9ENuz/RDbs/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU0fx/1NH8f9TR/H/U0fx/1JH8f9SRvH/Ukbx/1JG8f9SRvH/UEXs/05D5/9MQeL/S0Df/0tB3P9eVt//bmbi/3Fo4v9kXOD/VEvc/0k+3P9KP9//TEHk/0s/4/9JPdv/Rz3a/0c92v9HPdr/Rz3a/0o+4f9NQOr/T0Lw/05C8P9OQvD/TkLw/05B7/9OQe//TkHv/0xA6/9KPuX/SD3g/0Y73P9JPdr/YFbe/29m4f9rYuH/WU/d/0U52v9GOt7/Rzzi/0k95/9LP+7/Sz7u/0s+7v9LPu7/Sz7u/0k85/9HO+L/RTjd/0Q42v9QRNr/aF3f/3Bm4f9mW9//WU7d/0U52f9EN9v/RTjf/0Y55P9FOOH/QjbY/0I11/9CNNf/QjTX/0E01/9BNNf/QTTX/0Ez1/9BM9f/QDPX/0Az1/9AM9n/Qzbj/0Y47P9FOOz/RTjs/0U37P9FN+z/RTfs/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVEjy/1NI8v9TR/H/U0fx/1NH8f9TR/H/U0fx/1JH8f9SRvH/Ukbx/1JG8f9QRez/T0To/05D5v9NQuX/TEHk/0xB4/9MQeT/TULl/05B5v9OQuj/T0Pt/05C6f9NQeb/TEHl/0xA5f9MQOX/S0Dl/0xB6P9PQ+//T0Pw/09C8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05B7/9OQe//TEDq/0o/5/9JPuT/SD7i/0g84f9IPeL/ST3j/0o95f9KPuj/Sz/s/0w/7/9MP+//TD/v/0w/7/9LP+//Sz7u/0s+7v9KPuz/STzn/0g75P9HO+L/Rjrh/0Y54P9GOuH/Rzri/0c64/9HOub/Rzvo/0k87f9HO+j/Rjnk/0Y44v9FOOL/RTji/0U44v9FN+L/RTfi/0Q34v9EN+L/RDfi/0Q24v9EN+P/RTjp/0Y57f9GOO3/Rjjt/0Y47P9FOOz/RTjs/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVEjy/1RI8v9USPL/VEjy/1NI8v9TR/H/U0fx/1NH8f9TR/H/U0fx/1NH8f9SRvH/Ukbx/1JG8f9SRvD/UUXv/1FF7v9QRO//UUXw/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BD8P9QQ/D/T0Pw/09D8P9PQ/D/T0Pw/09C8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05B7/9OQe//TUDt/0xA7P9MQO3/TUHu/01A7/9NQO//TUDv/01A7/9MQO//TEDv/0w/7/9MP+//TD/v/0w/7/9LP+//Sz7u/0s+7v9LPu3/Sj7s/0o96/9KPuz/Sj3t/0o97v9KPe7/Sj3u/0o97v9KPO7/STzu/0k87v9JPO7/STzu/0k77f9IO+3/SDvt/0g77f9IOu3/SDrt/0c67f9HOu3/Rzrt/0c57f9HOe3/Rjnt/0Y57f9GOe3/Rjjt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVUny/1RJ8v9USPL/VEjy/1RI8v9USPL/VEjy/1NI8v9TR/H/U0fx/1NH8f9TR/H/U0fx/1NH8f9SRvH/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9RRfH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BD8P9QQ/D/T0Pw/09D8P9PQ/D/T0Pw/09C8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05B7/9OQe//TkHv/01B7/9NQe//TUHv/01A7/9NQO//TUDv/01A7/9MQO//TEDv/0w/7/9MP+//TD/v/0w/7/9LP+//Sz/v/0s+7v9LPu7/Sz7u/0s+7v9LPu7/Sj3u/0o97v9KPe7/Sj3u/0o97v9KPe7/STzu/0k87v9JPO7/STzu/0k77v9IO+3/SDvt/0g77f9IO+3/SDrt/0c67f9HOu3/Rzrt/0c57f9HOe3/Rjnt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1NI8v9TR/H/U0fx/1NH8f9TR/H/U0fx/1NH8f9SRvH/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9RRfH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BE8P9QQ/D/T0Pw/09D8P9PQ/D/T0Pw/09C8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05B7/9OQe//TkHv/01B7/9NQe//TUHv/01A7/9NQO//TUDv/01A7/9MQO//TEDv/0w/7/9MP+//TD/v/0w/7/9MP+//Sz/v/0s+7v9LPu7/Sz7u/0s+7v9LPu7/Sj3u/0o97v9KPe7/Sj3u/0o97v9KPe7/STzu/0k87v9JPO7/STzu/0k77v9IO+3/SDvt/0g77f9IO+3/SDrt/0c67f9HOu3/Rzrt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVUry/1VK8v9VSvL/VUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1NI8v9TR/H/U0fx/1NH8f9TR/H/U0fx/1NH8f9SRvH/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9RRfH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BE8P9QQ/D/T0Pw/09D8P9PQ/D/T0Pw/09C8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05B7/9OQe//TkHv/05B7/9NQe//TUHv/01A7/9NQO//TUDv/01A7/9MQO//TEDv/0w/7/9MP+//TD/v/0w/7/9MP+//Sz/v/0s+7v9LPu7/Sz7u/0s+7v9LPu7/Sj7u/0o97v9KPe7/Sj3u/0o97v9KPe7/STzu/0k87v9JPO7/STzu/0k77v9IO+3/SDvt/0g77f9IO+3/SDrt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVkry/1ZK8v9WSvL/VUry/1VK8v9VSvL/VUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1NI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9SRvH/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRfH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BE8P9QQ/D/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05B7/9OQe//TkHv/05B7/9NQe//TUHv/01A7/9NQO//TUDv/01A7/9MQO//TEDv/0w/7/9MP+//TD/v/0w/7/9MP+//Sz/v/0s+7v9LPu7/Sz7u/0s+7v9LPu7/Sj7u/0o97v9KPe7/Sj3u/0o97v9KPe7/STzu/0k87v9JPO7/STzu/0k77v9IO+3/SDvt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVkvz/1ZL8/9WS/P/Vkry/1ZK8v9WSvL/VUry/1VK8v9VSvL/VUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9SRvH/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRfH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BE8P9QQ/D/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05B7/9OQe//TkHv/05B7/9NQe//TUHv/01A7/9NQO//TUDv/01A7/9MQO//TEDv/0w/7/9MP+//TD/v/0w/7/9MP+//Sz/v/0s+7v9LPu7/Sz7u/0s+7v9LPu7/Sj7u/0o97v9KPe7/Sj3u/0o97v9KPe7/STzu/0k87v9JPO7/STzu/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV0vz/1dL8/9XS/P/Vkvz/1ZL8/9WS/P/Vkry/1ZK8v9WSvL/Vkry/1VK8v9VSvL/VUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9SR/H/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRfH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BE8P9QQ/D/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05C8P9OQe//TkHv/05B7/9NQe//TUHv/01A7/9NQO//TUDv/01A7/9MQO//TEDv/0w/7/9MP+//TD/v/0w/7/9MP+//Sz/v/0s+7v9LPu7/Sz7u/0s+7v9LPu7/Sj7u/0o97v9KPe7/Sj3u/0o97v9KPe7/STzu/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV0zz/1dM8/9XTPP/V0zz/1dL8/9XS/P/Vkvz/1ZL8/9WS/P/Vkry/1ZK8v9WSvL/Vkry/1VK8v9VSvL/VUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9SR/H/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRfH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BE8P9QQ/D/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/05C8P9OQvD/TkLw/05C8P9OQe//TkHv/05B7/9NQe//TUHv/01A7/9NQO//TUDv/01A7/9MQO//TEDv/0w/7/9MP+//TD/v/0w/7/9MP+//Sz/v/0s+7v9LPu7/Sz7u/0s+7v9LPu7/Sz7u/0o97v9KPe7/Sj3u/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWE3z/1hM8/9YTPP/V0zz/1dM8/9XTPP/V0zz/1dL8/9XS/P/Vkvz/1ZL8/9WS/P/Vkry/1ZK8v9WSvL/Vkry/1VK8v9VSvL/VUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9SR/H/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRvH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UETw/1BE8P9QRPD/UETw/1BE8P9QQ/D/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/09C8P9OQvD/TkLw/05C8P9OQe//TkHv/05B7/9NQe//TUHv/01B7/9NQO//TUDv/01A7/9NQO//TEDv/0w/7/9MP+//TD/v/0w/7/9MP+//Sz/v/0s+7v9LPu7/Sz7u/0s+7v9LPu7/Sz7u/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWE3z/1hN8/9YTfP/WE3z/1hM8/9YTPP/V0zz/1dM8/9XTPP/V0zz/1dL8/9XS/P/Vkvz/1ZL8/9WS/P/Vkvz/1ZK8v9WSvL/Vkry/1VK8v9VSvL/VUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9SR/H/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRvH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRPD/UUTw/1BE8P9QRPD/UETw/1BE8P9QQ/D/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/09C8P9OQvD/TkLw/05C8P9OQe//TkHv/05B7/9NQe//TUHv/01B7/9NQO//TUDv/01A7/9NQO//TEDv/0w/7/9MP+//TD/v/0w/7/9MP+//Sz/v/0s+7v9LPu7/Sz7u/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWE308llN8/9YTfP/WE3z/1hN8/9YTfP/WE3z/1hM8/9YTPP/V0zz/1dM8/9XTPP/V0zz/1dL8/9XS/P/Vkvz/1ZL8/9WS/P/Vkvz/1ZK8v9WSvL/Vkry/1VK8v9VSvL/VUny/1VJ8v9VSfL/VUny/1RJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9TR/H/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRvH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRfH/UUTw/1BE8P9QRPD/UETw/1BE8P9QQ/D/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/09C8P9OQvD/TkLw/05C8P9OQe//TkHv/05B7/9NQe//TUHv/01B7/9NQO//TUDv/01A7/9NQO//TEDv/0xA7/9MP+//TD/v/0w/7/9MP+//Sz/v8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWE70rFlO9P9ZTvT/WU70/1lN8/9YTfP/WE3z/1hN8/9YTfP/WE3z/1hM8/9YTPP/V0zz/1dM8/9XTPP/V0zz/1dL8/9XS/P/V0vz/1ZL8/9WS/P/Vkvz/1ZK8v9WSvL/Vkry/1VK8v9VSvL/VUry/1VJ8v9VSfL/VUny/1VJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9TR/H/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRvH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRfH/UUTw/1BE8P9QRPD/UETw/1BE8P9QQ/D/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/09C8P9OQvD/TkLw/05C8P9OQe//TkHv/05B7/9NQe//TUHv/01B7/9NQO//TUDv/01A7/9NQO//TEDv/0xA7/9MP+//TD/uqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV0/2HVpO9O1ZTvT/WU70/1lO9P9ZTvT/WU70/1lN8/9ZTfP/WE3z/1hN8/9YTfP/WE3z/1hM8/9YTPP/V0zz/1dM8/9XTPP/V0zz/1dL8/9XS/P/V0vz/1ZL8/9WS/P/Vkvz/1ZK8v9WSvL/Vkry/1VK8v9VSvL/VUry/1VJ8v9VSfL/VUny/1VJ8v9USfL/VEjy/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9TR/H/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRvH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRfH/UUTw/1BE8P9QRPD/UETw/1BE8P9QRPD/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/09C8P9OQvD/TkLw/05C8P9OQe//TkHv/05B7/9NQe//TUHv/01B7/9NQO//TUDv/01A7/9NQO7uTz3tHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFdP9h1aTvSsWU/08lpP9P9ZTvT/WU70/1lO9P9ZTvT/WU70/1lO9P9ZTfP/WE3z/1hN8/9YTfP/WE3z/1hM8/9YTPP/V0zz/1dM8/9XTPP/V0zz/1dL8/9XS/P/V0vz/1ZL8/9WS/P/Vkvz/1ZK8v9WSvL/Vkry/1VK8v9VSvL/VUry/1VJ8v9VSfL/VUny/1VJ8v9USfL/VEny/1RI8v9USPL/VEjy/1RI8v9TSPL/U0fx/1NH8f9TR/H/U0fx/1NH8f9TR/H/Ukbx/1JG8f9SRvH/Ukbx/1JG8f9SRvH/UUXx/1FF8f9RRfH/UUXx/1FF8f9RRfH/UUTw/1BE8P9QRPD/UETw/1BE8P9QRPD/UEPw/09D8P9PQ/D/T0Pw/09D8P9PQvD/T0Lw/09C8P9OQvD/TkLw/05C8P9OQe//TkHv/05B7/9OQe//TEHv8k1B7q9OQfEnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALKyslq2trb1ubm5/729vf/AwMD/w8PD/8fHx+TIyMg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzDLGxsbgwsLC/7+/v/+8vLz/ubm5/7W1tfewsLBiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC5ubkwvLy83r+/v//CwsL/xsbG/8rKyv/Ly8v4zMzMZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysrKXczMzPbKysr/xsbG/8LCwv+/v7//u7u74ra2tjUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAu7u7E8DAwLnFxcX/ycnJ/8zMzP/MzMz/zMzM/8zMzKLGxsYJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANra2gfMzMyRzMzM/8zMzP/MzMz/ycnJ/8XFxf/AwMDAubm5FgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKqqqgPIyMiIy8vL/szMzP/MzMz/zMzM/8zMzP/KysrMzc3NHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzc3NGsvLy8bMzMz/zMzM/8zMzP/MzMz/zMzM/8jIyJm/v78EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysrKTszMzPDMzMz/zMzM/8vLy//Ly8v/ysrK6szMzEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMw8ysrK5svLy//Ly8v/zMzM/8zMzP/Ly8vzzMzMVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrKyifLy8vWzMzM/8vLy//Ly8v/y8vL/8vLy/vLy8t3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrKymbKysr5y8vL/8vLy//Ly8v/zMzM/8vLy9vKysosAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIyMgOy8vLrsvLy//Ly8v/y8vL/8vLy//Ly8v/ysrKpczMzAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/v78Iy8vLncvLy//Ly8v/y8vL/8vLy//Ly8v/ysrKtdLS0hEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AcvLy3fKysr9y8vL/8vLy//Ly8v/y8vL/8vLy8/IyMghAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrKyh3Ly8vKy8vL/8vLy//Ly8v/y8vL/8rKyv7KysqI////AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLy8tKysrK78vLy//Ly8v/y8vL/8vLy//KysrsyMjIRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysrKP8rKyunLy8v/y8vL/8vLy//Ly8v/y8vL8snJyVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzc3NJMvLy9PLy8v/y8vL/8rKyv/Kysr/ysrK/MnJyXf///8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKyspmysrK+8rKyv/Kysr/y8vL/8vLy//Ly8vYzc3NKQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANTU1AzKysqqysrK/8rKyv/Kysr/ysrK/8rKyv/JycmxzMzMDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv7+/DMrKyqrKysr/ysrK/8rKyv/Kysr/ysrK/8vLy7LMzMwPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8BysrKb8rKyvvKysr/ysrK/8rKyv/Jycn/x8fH2MfHxykAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADGxsYkx8fH08nJyf/Kysr/ysrK/8rKyv/Kysr8ycnJgP///wIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMvLy0DKysrpysrK/8nJyf/IyMj/x8fH/8XFxfHGxsZRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMTExErGxsbux8fH/8jIyP/Jycn/ysrK/8rKyu3IyMhGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKysodyMjIysjIyP/Hx8f/xsbG/8XFxf/Dw8P+w8PDiP///wIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8Bw8PDd8PDw/3FxcX/xsbG/8fHx//IyMj/ycnJ0MrKyiIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv7+/CMbGxp7Gxsb/xcXF/8TExP/Dw8P/wcHB/7+/v7W/v78QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMTExA2/v7+uwcHB/8PDw//ExMT/xcXF/8bGxv/Hx8emzMzMCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFxcVmw8PD+sPDw//BwcH/v7+//729vf+7u7vbubm5LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAt7e3J7u7u9a9vb3/v7+//8HBwf/Dw8P/xMTE+8XFxXcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw8PDPMLCwue/v7//vb29/7u7u/+5ubn/tra287S0tFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACysrJNtra28Lm5uf+7u7v/vb29/8DAwP/CwsLrxcXFQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALy8vBu9vb3Hu7u7/7m5uf+2trb/srKy/66urv6srKyRv7+/BAAAAAAAAAAAqqqqA62trYCvr6/9s7Oz/7a2tv+5ubn/vLy8/76+vs29vb0fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC2trYHurq6mbe3t/+zs7P/rq6u/6urq/+hoJ//enRr6WhfUvJmXVHydW1l6J6dm/+rq6v/r6+v/7Ozs/+3t7f/ubm5osbGxgkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALOzs2Wurq74q6ur/5+enP92bWP/cWdc/29lWf9tY1f/a2FV/21jV/+enJr/q6ur/6+vr/izs7NlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACtra0yqKio4IeBev95cGX/d25j/3VsYP9zal7/cWhc/29lWv9+d2//p6en5K2trTgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApaWlFIJ5b/t/d2z/fXRq/3tyaP95cGX/d25j/3VsYf90bGD7qqqqGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIZ/dvKFfXP/g3tx/4F5b/9/d2z/fXVq/3tyaP95b2bwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI2GfauLhHr/iYF4/4d/dv+FfXT/g3tx/4F5b/9+d2ypAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJGIfxyRiYLtj4h//42Gff+LhHv/iYJ4/4aAdu2EenEbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACakYgclo+Gq5OMg/KSioHykIeArZCCfCUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////4AAAAAAAAAAAAAB/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAAAAAAA/4AAAAAAAAAAAAAB///4B///////4B/////8A///////wD/////+AP//////AH//////AH/////+AP//////wD/////8A///////4B/////4B///////8Af////gD///////+AP////AH////////gH///+Af////////wB///8A/////////4A///wB/////////8Af//gD//////////AP//AP//////////gD/8Af//////////wB/4A///////////8A/wD///////////+AfgH////////////AGAP////////////gAAf////////////4AB/////////////8AD/////////////+AH//////////////AP//////////////AP//////////////AP//////////////gf//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8='
$iconBytes       = [Convert]::FromBase64String($iconBase64)
# initialize a Memory stream holding the bytes
$stream          = [System.IO.MemoryStream]::new($iconBytes, 0, $iconBytes.Length)
$Form.Icon       = [System.Drawing.Icon]::FromHandle(([System.Drawing.Bitmap]::new($stream).GetHIcon()))

# Close xstore button
$closeButton = New-Object System.Windows.Forms.Button
$closeButton.Location = New-Object System.Drawing.Point(20,100)
$closeButton.Size = New-Object System.Drawing.Size(200,40)
$closeButton.Text = 'Close xStore'
$closeButton.Add_Click({ Invoke-UIProcess })
$closeButton.TabIndex = 1

# Close the application button
$cancelButton = New-Object System.Windows.Forms.Button
$cancelButton.Location = New-Object System.Drawing.Point(240,100)
$cancelButton.Size = New-Object System.Drawing.Size(200,40)
$cancelButton.Text = 'Exit'
$cancelButton.TabIndex = 2
$cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.CancelButton = $cancelButton

# start xstore button
$startButton = New-Object System.Windows.Forms.Button
$startButton.Location = New-Object System.Drawing.Point(20,40)
$startButton.Size = New-Object System.Drawing.Size(200,40)
$startButton.Text = 'Start xStore'
$startButton.Add_Click({ Restart-Stack -restartStack 'y' })
$startButton.TabIndex = 4

# Main information text
$label = New-Object System.Windows.Forms.Label
$label.Location = New-Object System.Drawing.Point(20,10)
$label.Size = New-Object System.Drawing.Size(400,20)
$label.Text = 'Please select action to begin.'

# Main information text
$loglable = New-Object System.Windows.Forms.Label
$loglable.Location = New-Object System.Drawing.Point(5,295)
$loglable.Size = New-Object System.Drawing.Size(500,20)
$loglable.Text = "LogFile: $loggingpath"
$loglable.font = [System.Drawing.Font]::new("Century Gothic", 10, [System.Drawing.FontStyle]::italic)
$loglable.ForeColor = 'lightgray'

# Checkbox for reboot of Application
$objTypeCheckboxRebootStack = New-Object System.Windows.Forms.Checkbox 
$objTypeCheckboxRebootStack.Location = New-Object System.Drawing.Size(20,145) 
$objTypeCheckboxRebootStack.Size = New-Object System.Drawing.Size(200,20)
$objTypeCheckboxRebootStack.Text = "Restart Stack on close?"
$objTypeCheckboxRebootStack.TabIndex = 3

# Checkbox for reboot of Machine
$objTypeCheckboxRebootMachine = New-Object System.Windows.Forms.Checkbox 
$objTypeCheckboxRebootMachine.Location = New-Object System.Drawing.Size(240,145) 
$objTypeCheckboxRebootMachine.Size = New-Object System.Drawing.Size(210,20)
$objTypeCheckboxRebootMachine.Text = "Reboot Machine on close?"
$objTypeCheckboxRebootMachine.TabIndex = 5

# Information progress label
$warn = New-Object System.Windows.Forms.Label
$warn.Location = New-Object System.Drawing.Point(240, 10)
$warn.font = [System.Drawing.Font]::new("Century Gothic", 16, [System.Drawing.FontStyle]::Bold)
$warn.Width = 200
$warn.Height = 80
$warn.TextAlign = [System.Drawing.ContentAlignment]::Middlecenter
$warn.Visible = $true
$warn.BackColor = 'gray'
$warn.Text = 'Ready'

# Add all controls to main form.
$form.Controls.Add($warn)
$form.Controls.Add($objTypeCheckboxRebootStack)
$form.Controls.Add($objTypeCheckboxRebootMachine)
$form.Controls.Add($label)
$form.Controls.Add($closeButton)
$form.Controls.Add($cancelButton)
$form.Controls.Add($Listview)
$form.Controls.Add($startbutton)
$form.Controls.Add($loglable)

# Make sure the form is top of z-index
$form.Topmost = $true

# Writes out the log to the file server for collation
Function Write-Log {
    param(
        [Parameter(Mandatory=$true)][String]$msg
    )
    $logtime = (get-date -Format "HH:mm:ss-ddMMyy")
    Add-Content -Path $loggingpath -Value $logtime" | "$env:Computername" | "$scriptVer" | "$msg
}

# Closes xStore
function close-Xstore {
        param(
            [Parameter(Mandatory=$true)][String]$closeXstore
        )

            #Where are the files that need to be removed stored?
            $xstorelockdir = @('C:\xstore\tmp','C:\xstore\tmp','C:\environment\tmp','C:\xstore-mobile\tmp','C:\eftlink\tmp');
            $xstoreProcessList = @((Get-Process | Where-Object {$_.ProcessName -ilike "xstore*"}),(Get-Process | Where-Object {$_.ProcessName -ilike "xmob*"}),(Get-Process | Where-Object {$_.ProcessName -ilike "xenv*"}))
            $runningProcCount = $xstoreProcessList.ProcessName.count

                #Add record to the list view field for action log.
                $time = (get-date -Format "HH:mm:ss")
                $listView.items.Insert(0,"[$time] Currently $runningProcCount xStore Processes Running.")

                if($closeXstore -ilike "y*"){

                            Write-log " : Closing xStore Software Stack, ($closeXstore) received."

                            if(($runningProcCount) -gt "0"){
                                foreach($ld in $xstorelockdir){
                                    if(test-path $ld){
                                        $lockfiles = Get-ChildItem -Path $ld | Where-Object {$_.Extension -ieq ".anchor"}
                                            foreach($l in $lockfiles){
                                                $anchorName = $l.Name
                                                if(test-path -Path $l.FullName){
                                                    #Add record to the list view field for action log.
                                                    $time = (get-date -Format "HH:mm:ss")
                                                    $listView.items.Insert(0,"[$time] Attempting Removal of $anchorName.")
                                                        Write-log " : Attempting Removal of $l."
                                                        Remove-Item -Path $l.FullName -force
                                                }else{
                                                    #Add record to the list view field for action log.
                                                    $time = (get-date -Format "HH:mm:ss")
                                                    $listView.items.Insert(0,"[$time] $anchorName has not been found.")
                                                        Write-log " : $l has not been found."
                                                }
                                            }
                                    }else{
                                        #Add record to the list view field for action log.
                                        $time = (get-date -Format "HH:mm:ss")
                                        $listView.items.Insert(0,"[$time] $ld does not exist.")
                                            Write-log " : $ld does not exist."
                                    }
                                }

                                $closeingXstore = 0
                                while((@((Get-Process | Where-Object {$_.ProcessName -ilike "xstore*"}),(Get-Process | Where-Object {$_.ProcessName -ilike "xmob*"}),(Get-Process | Where-Object {$_.ProcessName -ilike "xenv*"})).ProcessName).count -ge '1' -and $closeingXstore -le '20'){
                                        start-sleep -Seconds 1
                                        $closeingXstore += 1
                                }
                                    if($closeingXstore -le '20'){
                                        $timeToclose = ($closeingXstore)
                                            #Add record to the list view field for action log.
                                            $time = (get-date -Format "HH:mm:ss")
                                            $listView.items.Insert(0,"[$time] xStore closed in $timeToclose seconds.")
                                                Write-Log " : Xstore appears to be closed and it took $timeToclose seconds."
                                    }else{
                                        Write-Log " : ERROR - failed to close xStore."
                                            #Add record to the list view field for action log.
                                            $time = (get-date -Format "HH:mm:ss")
                                            $listView.items.Insert(0,"[$time] WARN - xStore has not closed in $timeToclose seconds.")
                                    }

                            }else{
                                #Add record to the list view field for action log.
                                $time = (get-date -Format "HH:mm:ss")
                                $listView.items.Insert(0,"[$time] xStore is not running.")
                                Write-log " : xStore is not running on $ENV:ComputerName @ $time."
                            }
                }else{
                    Write-log " : No Shutdown Requested, ($closexstore) received."
                }
}

# Restarts xStore
function Restart-Stack {
    param(
        [String]$restartStack
    )
    $warn.Visible = $true

            $warn.ForeColor = "black"
            $warn.BackColor = 'yellow'
            $warn.Text = "Attempting xStore Restart"

    #Add record to the list view field for action log.
    $time = (get-date -Format "HH:mm:ss")
    $listView.items.Insert(0,"[$time] Attempting Restart of xStore.")

        if($restartStack -ilike "y*" -or $CMDRestartStack -ilike "y*" -or $TRUE -eq $objTypeCheckboxRebootStack.Checked){

            Write-Log " : Attempting to start xStore via the start_eng.vbs file."
            Start-Process "Cscript.exe" -ArgumentList " C:\environment\start_eng.vbs //nologo" -WorkingDirectory 'C:\Windows\System32'

            $warn.ForeColor = "black"
            $warn.BackColor = 'yellow'
            $warn.Text = "Sleeping for 5 Seconds."
            Start-Sleep -Seconds 5

            $xstoreProcessList = @((Get-Process | Where-Object {$_.ProcessName -ilike "xstore*"}),(Get-Process | Where-Object {$_.ProcessName -ilike "xmob*"}),(Get-Process | Where-Object {$_.ProcessName -ilike "xenv*"}))
            $runningAfterRestart = ($xstoreProcessList.ProcessName).count

            if($runningAfterRestart -gt '0'){
                #Add record to the list view field for action log.
                $time = (get-date -Format "HH:mm:ss")
                $listView.items.Insert(0,"[$time] xStore has been launched.")

                $warn.BackColor = 'green'
                $warn.ForeColor = 'white'
                $warn.Text = "xStore Launched"

                #Add record to the list view field for action log.
                $time = (get-date -Format "HH:mm:ss")
                $listView.items.Insert(0,"[$time] INFO - xStore can take a while to load.")
            }else{
                $warn.BackColor = 'Red'
                $warn.ForeColor = 'white'
                $warn.Text = "ERROR - xStore Launch Failed."

                    #Add record to the list view field for action log.
                    $time = (get-date -Format "HH:mm:ss")
                    $listView.items.Insert(0,"[$time] ERROR - $runningAfterRestart number of xstore services launched. ")
            }

        }else{
            Write-log " : INFO - xstore restart not requested on $ENV:ComputerName. ($restartStack)."
        }
}

# Restarts The System
function invoke-SystemReboot {
    param(
        [String]$rebootMachine
    )

    $warn.Visible = $true

            $warn.ForeColor = "black"
            $warn.BackColor = 'yellow'
            $warn.Text = "Attempting System Reboot"

    #Add record to the list view field for action log.
    $time = (get-date -Format "HH:mm:ss")
    $listView.items.Insert(0,"[$time] Attempting Restart of $env:computername.")

        if($rebootmachine -ilike "y*" -or $TRUE -eq $objTypeCheckboxRebootMachine.Checked){

            Write-Log " : Rebooting $env:ComputerName."
            $listView.items.Insert(0,"[$time] System Reboot now.")
            Restart-Computer -Force | Out-Null

            $warn.ForeColor = "black"
            $warn.BackColor = 'yellow'
            $warn.Text = "Sleeping for 5 Seconds."
            Start-Sleep -Seconds 5

        }
}

Function Invoke-UIProcess {
    
    #$warn.Visible = $true

        #Add record to the list view field for action log.
        $time = (get-date -Format "HH:mm:ss")
        $listView.items.Insert(0,"[$time] Closing xStore Now")
            
            $warn.ForeColor = "black"
            $warn.BackColor = 'yellow'
            $warn.Text = "Attempting xstore close"

                close-xstore -closexstore 'y'

        #Add record to the list view field for action log.
        $time = (get-date -Format "HH:mm:ss")
        $listView.items.Insert(0,"[$time] xStore appears to be closed.")

            $warn.BackColor = 'green'
            $warn.ForeColor = 'white'
            $warn.Text = "xStore is closed."

            Start-Sleep -Seconds 1;

    if($TRUE -eq $objTypeCheckboxRebootMachine.Checked){
        
                $warn.ForeColor = "black"
                $warn.BackColor = 'yellow'   
                $global:warn.Text = "Invoking System Reboot"
                
                    invoke-SystemReboot -rebootMachine 'y'

    }elseIf($TRUE -eq $objTypeCheckboxRebootStack.Checked){
        
        $warn.ForeColor = "black"
        $warn.BackColor = 'yellow'   
        $global:warn.Text = "Attempting xStore Restart"
        
            Restart-Stack -restartStack 'y'
    }

    #Add record to the list view field for action log.
    $time = (get-date -Format "HH:mm:ss")
    $listView.items.Insert(0,"[$time] All Jobs Completed.")
        
        $warn.BackColor = 'green'
        $warn.ForeColor = 'white'
        $warn.Text = "Job Complete."
}

# This is for dealing with paramiterisation when calling from the command line. 
If($CMDCloseXstore -ilike "y*"){
    close-xstore -closexStore 'y'
    exit 0
}
If($CMDRestartSystem -ilike "y*"){
    close-xstore -closexStore 'y';
    invoke-SystemReboot -rebootMachine 'y';
    exit 0
}elseif($CMDRestartStack -ilike "y*"){
    close-xstore -closexStore 'y';
    Restart-Stack -restartStack 'y';
    exit 0
}

# If not called from the command line, show UI.
$form.ShowDialog()

exit 0